# @format

name: pomer-doro
services:
  astro:
    command: ["/bin/bash"]
    image: node:23-bookworm-slim
    ports:
      - 5432:5432
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /opt/pomer-doro
